version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - microservices

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - microservices

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservices

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "analytics_orders:1:1"
    depends_on:
      - zookeeper
    networks:
      - microservices

  order_service:
    build:
      context: ./order_service
    ports:
      - "8001:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - redis
      - rabbitmq
      - kafka
    networks:
      - microservices

  payment_service:
    build:
      context: ./payment_service
    ports:
      - "8002:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - redis
      - rabbitmq
      - kafka
    networks:
      - microservices

  notification_service:
    build:
      context: ./notification_service
    ports:
      - "8003:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - redis
      - rabbitmq
      - kafka
    networks:
      - microservices

  analytics_service:
    build:
      context: ./analytics_service
    ports:
      - "8004:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - redis
      - rabbitmq
      - kafka
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
