services:
  app:
    build:
      target: production
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
    volumes:
      - var_prod_cache:/var/www/html/var
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  db:
    environment:
      POSTGRES_DB: recruitment_db_prod
    volumes:
      - db_prod_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: ${COMPOSE_PROJECT_NAME:-recruitment}-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
    profiles:
      - monitoring

volumes:
  db_prod_data:
  var_prod_cache:
