services:
  app:
    build: .
    container_name: counter-app-dev
    environment:
      - APP_ENV=development
      - FLASK_DEBUG=1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=counterdb_dev
      - DB_USER=counteruser
      - DB_PASSWORD=counterpass
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - counter-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: counter-db-dev
    environment:
      - POSTGRES_DB=counterdb_dev
      - POSTGRES_USER=counteruser
      - POSTGRES_PASSWORD=counterpass
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - counter-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U counteruser -d counterdb_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: counter-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@counter.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - counter-network
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local

networks:
  counter-network:
    driver: bridge
