services:
  app:
    build: .
    container_name: counter-app-prod
    environment:
      - APP_ENV=production
      - FLASK_DEBUG=0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=counterdb_prod
      - DB_USER=counteruser_prod
      - DB_PASSWORD=counterpass_prod
    ports:
      - "80:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - counter-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  db:
    image: postgres:15-alpine
    container_name: counter-db-prod
    environment:
      - POSTGRES_DB=counterdb_prod
      - POSTGRES_USER=counteruser_prod
      - POSTGRES_PASSWORD=counterpass_prod
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - counter-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U counteruser_prod -d counterdb_prod"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  postgres_prod_data:
    driver: local

networks:
  counter-network:
    driver: bridge
